# Executing tests triggered by pull requests
on: pull_request

name: Test

jobs:
  gitHubActionForPytest:
    name: GitHub Action for pytest
    runs-on: ubuntu-latest
     
    steps:
    - uses: actions/checkout@master
    - name: GitHub Action for pytest
      uses: cclauss/GitHub-Action-for-pytest@master
      with:
        args: python setup.py install && pytest

  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install Python dependencies
        run: pip install black flake8

      - name: Run linters
        uses: samuelmeuli/lint-action@v1
        with:
          github_token: ${{ secrets.github_token }}
          # Enable linters
          black: true
          flake8: true
